version: "3.7"
services:
  frozen_flame:
    container_name: palworld-server
    build: .
    image: ghcr.io/ragingdave/palworld-docker:main
    #network_mode: "host"
    volumes:
      - "/path/to/config:/config"
    ports:
      - 7779:7779
      - 7780:7780/udp
      - 27017:27017/udp
    expose:
      - 7779
      - 7780/udp
      - 27017/udp
    environment:
      - "SERVER_NAME=PalworldServerByMe"
      - "SERVER_QUERY_PORT=7780"
      - "SERVER_PORT=7779"
      - "RCON_PORT=27017"
      - "RCON_PASSWORD=password"
      - "MAXPLAYERS=10"
      - "SERVERPASSWORD=password"
      - "DAYDURATION=3600" #How long a day lasts
      - "PUID=2198"
      - "PGID=2198"
      - "TZ=Etc/UTC"
    #tmpfs:
    #  - "/run:exec,mode=777"
    #  - "/tmp:exec,mode=777"
    restart: "unless-stopped"
